export { default as Header_1 } from './Header/Header_1'
export { default as Header_2 } from './Header/Header_2'
export { default as Home } from './Home/Home'
export { default as About } from './About/About'
export { default as Skill } from './Skill/Skill'
export { default as Project } from './Project/Project'
export { default as Contact } from './Contact/Contact'
export { default as Footer } from './Footer/Footer'

export { default as Socialicons } from './Socialicons/Socialicons'
export { default as ScrollToTop } from './ScrollToTop/ScrollToTop'